source :rubygems

group :development do
  gem 'guard'
  gem 'rb-inotify', :require => false
  gem 'rb-fsevent', :require => false
  gem 'rb-fchange', :require => false
  gem 'guard-process'
  gem 'guard-coffeescript'
end
